name: Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run Maven Tests
      run: mvn -B test --file ./purchasingms/pom.xml

  build:
    name: Build Maven Package
    runs-on: ubuntu-latest
    needs: tests

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('./purchasingms/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build package jar
      run: mvn -B package -DskipTests --file ./purchasingms/pom.xml
    - name: Upload .jar
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: ./purchasingms/target/app.jar

  deploy:
    name: Deploy on AWS Elastic Beanstall
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact jar
      uses: actions/download-artifact@v4
      with:
        name: artifact
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secret.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secret.AWS_SECRET_ACCESS_KEY }}
        use_existing_version_if_available: true
        wait_for_environment_recovery: 120
        application_name: app-springboot
        environment_name: App-springboot-env
        version_label: ${{ github.SHA }}
        region: us-east-1
        deployment_package: app.jar
